---
vms:
  - name: "puppet-master"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles: [ "hosts", "1gb-memory", "gitlab", "puppet_master", "customize_pe_via_hiera", "centos", "auto_net" ]

  - name: "gitlab-server"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles: [ "posix_agent", "puppet_agent", "centos", "1gb-memory" ]

